### ISSUE TITLE
Items found in dungeon glitch.

### ISSUE THREAD

**Issue by Cracky4589** [KawaiiBone/LethalCompanyRemnants#32] opened 2024-05-22 01:38 UTC
Hello, when loading a save, the items found in dungeon with this mods bugs. When we take the item we then cannot drop it or cannot interact anymore. The items do not appear as the same between host and client. 

Here my code in case you need it : 018f9df2-d442-b718-da12-0945d2227926

**Comment by KawaiiBone** [comment] 2024-05-22 06:40
This could be the same issue regarding the other bug that is known.
An incompatibility bug that makes the Remnants mod unable to clean up the remnant items.
If that is the case, then normally this issue should be fixed on the next update.

Thank you for reporting the bug.

**Comment by KawaiiBone** [comment] 2024-05-22 07:03
This specific issue seems to not happen when I play test it.
Could you elaborate more?

The issue seems to be not related to the one I mentioned above and could also be not caused by this mod.

**Comment by Cracky4589** [comment] 2024-05-22 13:33
Well after playing a bit, it look like a desync. Because many items found in dungeon who bugged was visible for me (client) but the host don't see them. When I take one of those items, it bug me and he host see something else in my hand, like a scrap or else. At some point the bugged items disappear when reloading the save and me restarting my game.

**Comment by KawaiiBone** [comment] 2024-05-24 07:17
The next patch will be an update on cleaning up remnant items.
Hopefully this will fix the issue you are having.
If not then it might really be an issue related to incompatibility with another mod.

**Comment by Cracky4589** [comment] 2024-06-01 21:37
The bug still happen after the update.

**Comment by KawaiiBone** [comment] 2024-06-02 14:29
That is unfortunate, could you maybe send me the log file of what happened during that game when the issue appeared?
This could help me more to identify the bug and see which mod creates this compatibility issue with this mod.

**Comment by Cracky4589** [comment] 2024-06-02 19:44
I could do that next time I play if the bug still happen. How do I do a log file? I never do that yet.

**Comment by KawaiiBone** [comment] 2024-06-03 07:58
A log file gets automatically created when you play the game, the file is called LogOutput.log.
It stores the text of the other screen that opens whenever you play a modded game of Lethal Company.
Thunderstore:
- If you use the thunderstore app you can find it by going into settings when you are in the profile where the bug happens.
- Go to locations and then click on Browse profile folder. 
- A folder will pop-up and you need to click on the BepInex folder, there you find the LogOutput.log file.

Steam:
- If you only use steam then go to the same place you put in the mod.
- Click on the BepInex folder, there you find the LogOutput.log file.

Just paste the LogOutput.log file here so I can take a look at it.
The reason why I ask you also to do this, is because the problem seems to only happen when you play with other people and are not the host. This means it is more difficult to test it for me.
Thank you for your help.

![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/159925618/e674d502-c335-4651-bc66-00cc3cdd29b7)

**Comment by Cracky4589** [comment] 2024-06-04 16:19
[LogOutput.log](https://github.com/user-attachments/files/15567563/LogOutput.log)

Here the log of my last game when the bug happen.

**Comment by KawaiiBone** [comment] 2024-06-10 07:01
Sorry that it is taking so long for the bug fix, i'm creating a new way to despawn remnant items that could fix this issue.
I still have not found the mod that causes this incompatibility issue.
Thank you for your patience.

**Comment by KawaiiBone** [comment] 2024-06-17 10:57
Does this issue still occur on the latest update?

**Comment by Cracky4589** [comment] 2024-06-17 22:25
Hello, I'll tell you when we gonna play Lethal again. Thanks for the update

**Comment by Cracky4589** [comment] 2024-06-21 22:10
As for now everything seem to be fine. We didn't encounter the bug again.

**Comment by Cracky4589** [comment] 2024-06-22 01:17
> As for now everything seem to be fine. We didn't encounter the bug again.

Ahh nvm it happen again. Same way, reloading a save and I took an item I got stuck again.

**Comment by KawaiiBone** [comment] 2024-06-24 08:30
I'm sorry, but I don't think I can fix this issue now.
Since I can't find the issue by myself alone, and it seems to be a very specific issue that does not occur with other people.
I would suggest not using the Remnants mod with mods you are using now, since one of them creates the compatibility issues with the Remnants mod and I can't find it.
You can maybe find it, if you disable some mods and test it that way.

**Comment by Cracky4589** [comment] 2024-06-24 21:40
Alright, I appreciate the support. We will live with untill it go away by itself. But I think I need to remake my modpack. If at anytime I find what the issue is I'll write it here.

**Closed as completed** 2024-09-09 07:58 UTC
Labels: bug
