### ISSUE TITLE
[Bug] Makes Other Modded Shop Items Unpurchaseable

### ISSUE THREAD

**Issue by xKiva** [KawaiiBone/LethalCompanyRemnants#28] opened 2024-04-29 10:20 UTC
Noticed in a run earlier that all the modded store items which were spawning as scrap weren't able to be purchased from the terminal as usual. The modded items came from lethalthings.

**Comment by KawaiiBone** [comment] 2024-04-29 11:54
Could you tell me more how this happened?
Can you send me the profile code, to test and see how this issue works.

Thank you for reporting the bug.

**Comment by xKiva** [comment] 2024-04-30 10:03
Not sure what caused the bug to happen but when you try to buy an item from another mod it says something along the lines of "this action was not compatible with this item".
Profile Code: 018f2e73-5861-2aaa-64a9-4e37333fc3a4

**Comment by KawaiiBone** [comment] 2024-04-30 10:45
I do will say there has never been a bug with items being unable to be purchased that is caused by the Remnants mod.
So there is a big chance that it is not because of the Remnants mod.
I will test now the mod collection you have send me and get back to you soon.

**Comment by KawaiiBone** [comment] 2024-04-30 11:22
I tested the mod collection, not updated and fully updated version.
I have not come across the issue that you have stated here.
With that, store items are separate from remnant items, because normally they just get copied and made into a new object.
That is why you can scan remnant items and not normal store items.

**Comment by xKiva** [comment] 2024-05-01 10:39
Ok sweet thanks for checking, I'll update everything later and double check if that solves it.
haven't updated the profile because some of the newly updated mods bricked travelling to the company building.
If i find anything new I'll leave it here if that's fine.

**Comment by KawaiiBone** [comment] 2024-06-02 14:40
For now I will close this issue, since there has been no issues found anymore.

**Closed as completed by KawaiiBone** 2024-06-02 14:40 UTC
