### ISSUE TITLE
Performance Issues || bugged bodies

### ISSUE THREAD

**Issue by OminousDiscovery** [KawaiiBone/LethalCompanyRemnants#39] opened 2024-08-06 06:16 UTC
My games FPS lowers when I use this mod. I would give you more details but I dont really know how to

**Comment by KawaiiBone** [comment] 2024-08-06 07:08
Thank you for reporting the bug.

I think I know why there are performance issues.
It is due to a bug in this mod that is caused by the new update of the game.
The default bodies that this mod spawns are the one that are bugged and causes performance issues.
I am already working on this issue, but you can avoid it by spawning the bodies as a prop rather then as scrap.
By going into the config to the section _GeneralBody_ and _setting Should bodies be scrap_ to false.

I hope this helps.

**Comment by KawaiiBone** [comment] 2024-08-07 14:14
This issue should be fixed now on the current version, I will close this issue in a couple of weeks unless it is still present.

**Closed as completed** 2024-08-30 08:20 UTC
Labels: bug
